modLoader = "javafml"
loaderVersion = "[37,)"
#issueTrackerURL = ""
license = "LGPLv3"

[[mods]]
modId = "wanderers_spawn"
version = "${version}"
displayName = "Wanderer's Spawn"
authors = "macbrayne"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.wanderers_spawn]]
modId = "forge"
mandatory = true
versionRange = "[37,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wanderers_spawn]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17.1,)"
ordering = "NONE"
side = "BOTH"